
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from './providers'
import NavBar from "./ui/Navbar/NavBar";
import Footer from "./ui/Footer/Footer";
import { has } from "./cookies/cookiesHandler";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  const isLogged =  await has("access_token")
     return (
     <html lang="en">
        <body className={inter.className}>
        <Providers>
          {isLogged? children : <><NavBar/> {children}<Footer/></> }
        </Providers>  
          </body>
      </html>
     )   
}
